name: Blog - Shawinder Sekhon.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# staticman (comments) configuration
staticman_url: https://shawinder-github-staticman.herokuapp.com/v2/entry/shawinder/shawinder.github.io/master/comments

reCaptcha:
    # the siteKey is used as-is (no encryption)
    siteKey: 6LdQA9MZAAAAADz1HZslJMDLD3g5Fius5IhMR55y
    # the secret is the encrypted blob you got back from the encrypt call
    secret: TqD07TFVkBBfF1lTAs7h5GZDsEP90xMvuJijecnMPb1SLHitYM/b7y3FKE04j69//YKw9qs5Un8W0sJlJggX2zpGkIBU94fmhEjbXrVy81vxfmtZ9yB49BqhdC1LtRD7dpbPRzpW7F1OR5ula+s4z3xq0DGpnGpmT2xoGsqZVrjY5f1VQdVgTPNn7qwfADVftAGguMcnw8YV2rUAja8aRb4cQmd4q9OjYwAC5QlOyGsgVNGS2oNBul044XwMQxNhAh8Lt6y520eKZCV2b3CPGfOL99BtmMrodQvy+kxs2xIMIL+5olioJAk+PQ9rkaUXkKHKD4x3zs+045eNHUOZ/Pa75JNHOzS85VfRyDTsv1TevIviQBafg4jlGk6qkeiFVytjALcLi1GnzuXMsVh8eiWPPXp/fFilAq2uo0IRMT4UbUOtVMyCnuVcGRp3twOXkLTxuOwtE4tFTHsRu8EOCQ1IQd/Y71I8bX/V3L871OiBse5H9iupB3FS7CMU0XoM02SkclSzb9YVqHT+8/7dEWFrD58pp4F3qH7eVO7RxMvZ0CIu0ZKKlez5yNMKvkMuebAcfdKK35Z1pPlge/7W96Jue2wb4SHQ8X6hjpyS/gmpUoXhq/K0AjVjgX/H6YzGQBbfexjeF+LfN+lIoWG99fUahsTSTmr8BMWnrxGVUP8=
