name: Blog - Shawinder Sekhon.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# staticman (comments) configuration
staticman_url: http://comments.shawinder.com/v2/entry/shawinder/shawinder.github.io/master/comments

reCaptcha:
    # the siteKey is used as-is (no encryption)
    siteKey: 6LdQA9MZAAAAADz1HZslJMDLD3g5Fius5IhMR55y
    # the secret is the encrypted blob you got back from the encrypt call
    secret: cJMMDrYHRTLvwgYfVP8EqIaUxCgB9tEdl13+12pkQKIsc7Mp3S5Gi+DWJj7RF/aiH5KMgiwqIaUq8br6Al1nsIYB+NN11kEzS8ZPY1pkXKadVR5nGw6pE94rB9a2AiTVYtq3NU/vPPMTmRsmmlw5RSSBYsFmN9kUrb8BTOfxSEW5AAQxsoPAWTXG9Um2s7AOJIyaAAiR06Hs3H6rUcffEdKmSjPhsyHTAy2KRjS7SSiOcvWNA7B9eD4+/2bti0buYYHOe7bggJi91PzK7hp6y8fv2AxdZAtmJl3FhfDUuoDOmc8/8bdQP+65Y+WuR9g6zpMDzrRjYGh63jelxXPa6G8oPN7eg5jTzDhZxOSV/mbym5pZz4RGc2SwgFYy4XDfcEib66H6ZCVopM5a1TjaguJmtiW7oQUxl5HZlK0b/jcq0IwictFAUu2KW+uOohFau0l5x9w939HN2OJ0/NvbaYUBlCwfmnMeODiF96/7F985D2SlBnWxc5+LrU5dPeVztq0ujNYzyyRlpKWRrV3AIR5WB3TkQlnOq3ILy13lWEj5eHBmragiZ8IME4ydrnyiNcbMSWmimXoSm/F5Bz+NoKZCtL6ilkviCBW4wHduJigQ6B5lalFXJMdaxJeC4uhhqtAm+S3LFiVI9GAUvVcVk95xBQ1/vXJ3KM/fRP6g5q8=
