name: Blog - Shawinder Sekhon.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# staticman (comments) configuration
staticman_url: https://shawinder-github-staticman.herokuapp.com/v2/entry/shawinder/shawinder.github.io/master/comments
